### ISSUE TITLE
Version 1.2.7 is still not on NuGet

### ISSUE THREAD

**Issue by sirudog** [macgile/DataGridFilter#114]
Hi,
Seems like 1.2.7 is still not available from NuGet.
Found this relevant issue https://github.com/macgile/DataGridFilter/issues/89

Can you please publish it?
Many thanks

**Comment by sirudog** [comment]
In the meantime, I tried to use the currently available 1.2.6 version from Nuget, but I could not. The assembly in the package is not signed, so I get `Referenced assembly does not have a strong name` error. Please sign the assembly in the next release before publising it. Thanks

**Comment by macgile** [comment]
Hi,

I didn't release 1.2.7 because there are issues with using the nuget package, Filterdatagrid stays invisible in the test app, as if I had set visibility to "Hidden"
As soon as I have solved this problem I will publish the new package.

I would take this opportunity to sign the assembly, it makes me think that the problem cited above may be the cause.

**Comment by sirudog** [comment]
Thanks for the quick reply!
I am currently using 1.2.7 (source code downloaded and added to my solution), and first I also encountered the issue of invisible datagrid.
What fixed it for me was to use this way of referencing the style, even though it was stated in the readme it is only for version 1.2.6
```
<Style x:Key="FilterDatagridStyle" 
BasedOn="{StaticResource {ComponentResourceKey TypeInTargetAssembly=control:FilterDataGrid, 
ResourceId=FilterDataGridStyle}}" 
TargetType="{x:Type control:FilterDataGrid}">
</Style>
```

**Comment by macgile** [comment]
Nuget version 1.2.7 is available
