### ISSUE TITLE
Clear filter not working properly

### ISSUE THREAD

**Issue by grzegorzczarnecki85** [macgile/DataGridFilter#29]
Steps to reproduce:
1.	Use filter on column First name and select only Aaron
![step1](https://user-images.githubusercontent.com/84695885/135717118-912a04dc-cdbd-45ee-b249-50a013c11043.png)

2.	Use filter on column Last name and select only Baacecyyun
 ![step2](https://user-images.githubusercontent.com/84695885/135717123-99f35e33-e64f-4a10-9bf3-1e64f51100f0.png)

3.	Clear filter on column First name
 ![step3](https://user-images.githubusercontent.com/84695885/135717125-22651903-235b-4e6e-8857-98a2d16ce077.png)

4. Filter on Last name should remain the same (only Baacecyyun) and we should get one record in table but we get randomly selected object in Last name column filter
![step4](https://user-images.githubusercontent.com/84695885/135717417-590b5242-709f-43bb-b5d0-217a3af64ed6.png)

**Comment by macgile** [comment]
This behavior is due to the fact that the filters act on the view of the "datagrid" (the rows displayed) and not on the entire collection (source items).
The "LastName" filter acts against the list of rows displayed after the "FirstName" filter is applied.
So when you release the "First Name" filter, all the filtered lines are visible again because they are unfiltered, only the lines filtered by the last filter are.

**Comment by macgile** [comment]
The "testing" branch works exactly like excel, you can use it instead of the current version.

best regards
